# Generated by Django 2.1.3 on 2019-01-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190106_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='sign_up',
        ),
    ]
