# Generated by Django 2.1.3 on 2019-01-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190107_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_up',
            new_name='signuptable',
        ),
    ]
