# Generated by Django 2.1.3 on 2019-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190107_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptable',
            name='uname',
            field=models.CharField(max_length=50),
        ),
    ]
